### ISSUE TITLE
How can i make sure core plugins are upto date with RC core plugins?

### ISSUE THREAD

**Issue by srikanthkolli** [andela/blade-runner-rc#16]
I saw PR for static pages feature which is very useful and also I see most of the customisations are done inside the core plugins. My question is if RC updates their core plugins and i want to make sure those changes are present in my project. How can i update the core plugins without affecting the changes done in balde runner rc? Is it possible to stay upto date with RC core plugins?

**Comment by missating** [comment]
Hello,  At the moment:

**if there is an update on RC, this might clearly be a problem, and if you want to make sure the updates made on that PR are maintained after an update, the only sure way is to create a custom plugin that provides this functionality.** 

Our team is currently working on extracting the updates in the pull request to a separate plugin so as to maintain changes if there is ever an update on the main RC core plugins.
